### ISSUE TITLE
fails to compile with rustc 1.87.0 (17067e9ac 2025-05-09)

### ISSUE THREAD

**Issue by DHouldershaw** [wdecoster/cramino#44]
Hi,
 Running `cargo install cramino` fails with:

> error[E0034]: multiple applicable items in scope
>    --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-22.0.0/src/compute/kernels/temporal.rs:232:53
>     |
> 37  |                     Some(dt) => $builder.append_value($convert(dt.$extract_fn())),
>     |                                                                   ----------- due to this macro variable
> ...
> 232 |             extract_component_from_array!(array, b, quarter, value_as_datetime, |h| h
>     |                                                     ^^^^^^^ multiple `quarter` found
>     |
> note: candidate #1 is defined in an impl of the trait `ChronoDateExt` for the type `T`
>    --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-22.0.0/src/compute/kernels/temporal.rs:134:5
>     |
> 134 |     fn quarter(&self) -> u32 {
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^
>     = note: candidate #2 is defined in an impl of the trait `Datelike` for the type `chrono::NaiveDateTime`
> help: disambiguate the method for candidate #1
>     |
> 37  -                     Some(dt) => $builder.append_value($convert(dt.$extract_fn())),
> 37  +                     Some(dt) => $builder.append_value($convert(ChronoDateExt::quarter(&dt))),
>     |
> help: disambiguate the method for candidate #2
>     |
> 37  -                     Some(dt) => $builder.append_value($convert(dt.$extract_fn())),
> 37  +                     Some(dt) => $builder.append_value($convert(Datelike::quarter(&dt))),
>     |
> 
> error[E0034]: multiple applicable items in scope
>    --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-22.0.0/src/compute/kernels/temporal.rs:240:17
>     |
> 93  |                                     $builder.append_value($convert(dt.$extract_fn()));
>     |                                                                       ----------- due to this macro variable
> ...
> 240 |                 quarter,
>     |                 ^^^^^^^ multiple `quarter` found
>     |
> note: candidate #1 is defined in an impl of the trait `ChronoDateExt` for the type `T`
>    --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-22.0.0/src/compute/kernels/temporal.rs:134:5
>     |
> 134 |     fn quarter(&self) -> u32 {
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^
>     = note: candidate #2 is defined in an impl of the trait `Datelike` for the type `chrono::NaiveDateTime`
> help: disambiguate the method for candidate #1
>     |
> 93  -                                     $builder.append_value($convert(dt.$extract_fn()));
> 93  +                                     $builder.append_value($convert(ChronoDateExt::quarter(&dt)));
>     |
> help: disambiguate the method for candidate #2
>     |
> 93  -                                     $builder.append_value($convert(dt.$extract_fn()));
> 93  +                                     $builder.append_value($convert(Datelike::quarter(&dt)));
>     |
> 
which seems to be a clash between arrow and chrono (crates?). Can any one suggest a fix for this ?
Many Thanks.

**Comment by DHouldershaw** [comment]
Hi, many thanks for looking at the problem. When I try the binary from cramino-linux.zip, v1.0, on Almalinux 8, CentOS 8 or CentOS 7 I get:

```
-> ./cramino 
./cramino: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./cramino)
./cramino: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by ./cramino)
./cramino: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./cramino)
./cramino: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./cramino)
./cramino: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./cramino)

```
Which version of linux is cramino compiled for ?

Many Thanks for any help you can give. Cheers, Dave H.

**Comment by wdecoster** [comment]
Ah, could you try the musl build?
This one: https://github.com/wdecoster/cramino/releases/download/v1.0.0/cramino-musl.zip

**Comment by wdecoster** [comment]
Do you have very few (aligned) reads in that bam file that resulted in the error?

**Comment by DHouldershaw** [comment]
Hi, Sorry I don't know, it's not my data, I'm only setting the software up for one of our Lecturers. I'll ask the question...
Cheers, Dave H.

**Comment by DHouldershaw** [comment]
Hi, reply from the Lecturer:

> In fact there are 0 aligned reads… as it is just an unaligned bam after classifying the barcodes post-basecalling…

So, using the --ubam flag produces a result :) I think I can hand it over to the Lecturer to interpret now :)

Many Thanks for your help and guidance. Cheers, Dave H.
